import { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';

import forestImage from '../../assets/images/forest.png';
import oceanImage from '../../assets/images/ocean.jpg';
import mountainImage from '../../assets/images/mountain.jpg';
import desertImage from '../../assets/images/desert.jpg';
import jaguarImage from '../../assets/images/jaguar.jpg';
import eagleImage from '../../assets/images/eagle.jpg';
import whaleImage from '../../assets/images/whale.avif';
import landscapeImage from '../../assets/images/paisaje2.avif';

const PLACES = [
  { id: 'amazon', name: 'Amazon Basin', region: 'South America', country: 'Brazil · Peru · Colombia', type: 'Forest', image: forestImage, x: 28, y: 64, description: 'A living network of rivers and rainforest where floodplains, canopy and forest floor form different worlds.', fact: 'The Amazon River carries more water than any other river on Earth.', color: '#9caf88' },
  { id: 'galapagos', name: 'Galápagos Islands', region: 'South America', country: 'Ecuador', type: 'Ocean', image: jaguarImage, x: 20, y: 55, description: 'Volcanic islands where isolation created fearless wildlife and helped inspire the study of evolution.', fact: 'Marine and land ecosystems meet here in one of the Pacific’s most unusual archipelagos.', color: '#8db8c7' },
  { id: 'sahara', name: 'Sahara', region: 'Africa', country: 'North Africa', type: 'Desert', image: desertImage, x: 51, y: 43, description: 'A sea of stone, sand and sky stretching across the top of Africa, crossed by ancient trade routes.', fact: 'The Sahara is the largest hot desert in the world.', color: '#d1b77a' },
  { id: 'serengeti', name: 'Serengeti', region: 'Africa', country: 'Tanzania · Kenya', type: 'Savanna', image: eagleImage, x: 55, y: 61, description: 'Open grasslands shaped by seasonal rain, grazing herds and some of the planet’s most recognisable predators.', fact: 'The annual migration moves millions of wildebeest, zebra and gazelles across the plains.', color: '#d2a56f' },
  { id: 'himalaya', name: 'Himalaya', region: 'Asia', country: 'Nepal · India · Bhutan', type: 'Mountains', image: mountainImage, x: 75, y: 42, description: 'A dramatic wall of peaks, glaciers and valleys where altitude changes life within a few kilometres.', fact: 'Mount Everest rises 8,849 metres above sea level.', color: '#c9c1a5' },
  { id: 'great-barrier-reef', name: 'Great Barrier Reef', region: 'Oceania', country: 'Australia', type: 'Ocean', image: oceanImage, x: 88, y: 70, description: 'A vast constellation of coral reefs, islands and lagoons visible from space and alive with colour.', fact: 'It is the world’s largest coral reef system, made of thousands of individual reefs.', color: '#8db8c7' },
  { id: 'patagonia', name: 'Patagonia', region: 'South America', country: 'Chile · Argentina', type: 'Mountains', image: landscapeImage, x: 29, y: 82, description: 'Wind-carved plains, blue lakes and granite towers at the southern edge of the Americas.', fact: 'Patagonia contains temperate forests, steppe, glaciers and some of the world’s clearest night skies.', color: '#a8b69b' },
  { id: 'arctic', name: 'Arctic Circle', region: 'Arctic', country: 'Across the northern ocean', type: 'Polar', image: whaleImage, x: 57, y: 17, description: 'A shifting world of sea ice, tundra, whales and long seasonal light at the top of the planet.', fact: 'The Arctic is an ocean surrounded by continents, unlike Antarctica, which is a continent surrounded by ocean.', color: '#b7d7d5' },
];

const FILTERS = ['All', 'Africa', 'Asia', 'Europe', 'North America', 'South America', 'Oceania', 'Arctic'];

export function Explore() {
  const [selectedId, setSelectedId] = useState('amazon');
  const [filter, setFilter] = useState('All');
  const selected = PLACES.find((place) => place.id === selectedId) || PLACES[0];
  const visiblePlaces = useMemo(() => filter === 'All' ? PLACES : PLACES.filter((place) => place.region === filter), [filter]);

  const selectPlace = (place) => {
    setSelectedId(place.id);
    document.getElementById('atlas-detail')?.scrollIntoView({ behavior: 'smooth', block: 'center' });
  };

  return (
    <main className="min-h-screen overflow-hidden bg-[#07100b] text-white">
      <section className="relative border-b border-white/10 px-6 pb-20 pt-40 md:px-10 md:pb-28"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-10 md:flex-row md:items-end"><div className="max-w-3xl"><p className="text-[10px] uppercase tracking-[0.5em] text-[#9caf88]">Wild & Free field atlas</p><h1 className="mt-6 text-5xl font-light leading-[0.95] tracking-tight sm:text-7xl md:text-8xl">The world,<br /><span className="text-white/35">in living points.</span></h1></div><p className="max-w-sm text-sm leading-8 text-white/45">Move across the map. Meet places where geography, wildlife and human stories have been shaping one another for centuries.</p></div><div className="mt-16 flex flex-wrap gap-3 text-[9px] uppercase tracking-[0.2em] text-white/45"><span className="border border-white/10 px-4 py-2">08 locations</span><span className="border border-white/10 px-4 py-2">07 regions</span><span className="border border-white/10 px-4 py-2">One living planet</span></div></div></section>

      <section className="mx-auto max-w-7xl px-6 py-16 md:px-10 md:py-24"><div className="mb-8 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-[10px] uppercase tracking-[0.4em] text-[#9caf88]">Interactive atlas</p><h2 className="mt-3 text-3xl font-light">Choose a point of wonder.</h2></div><p className="max-w-sm text-xs leading-6 text-white/35 md:text-right">Each marker opens a different landscape. Dragging is not required; curiosity is.</p></div><div className="mb-8 flex gap-2 overflow-x-auto pb-2">{FILTERS.map((item) => <button key={item} type="button" onClick={() => setFilter(item)} className={`whitespace-nowrap border px-4 py-2 text-[9px] uppercase tracking-[0.18em] transition ${filter === item ? 'border-[#9caf88]/70 bg-[#9caf88]/15 text-[#dfead3]' : 'border-white/10 text-white/35 hover:border-white/30 hover:text-white/65'}`}>{item}</button>)}</div>
        <div className="relative min-h-[530px] overflow-hidden rounded-3xl border border-[#9caf88]/20 bg-[#0c1b13] shadow-2xl shadow-black/30 md:min-h-[650px]"><div className="absolute inset-0 opacity-30" style={{ backgroundImage: 'linear-gradient(rgba(156,175,136,0.16) 1px, transparent 1px), linear-gradient(90deg, rgba(156,175,136,0.16) 1px, transparent 1px)', backgroundSize: '54px 54px' }} /><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_50%,rgba(45,103,70,0.4),transparent_58%)]" /><svg viewBox="0 0 1000 600" className="absolute inset-0 h-full w-full opacity-80" aria-label="Stylized world map" role="img" preserveAspectRatio="none"><path d="M80 155 132 105 205 92 264 130 285 205 244 242 208 228 173 270 125 245 102 203 61 190Z" fill="#31563a" stroke="#769678" strokeWidth="2" /><path d="M295 90 358 58 430 70 486 111 478 165 433 196 400 245 362 298 328 271 312 213 275 172Z" fill="#31563a" stroke="#769678" strokeWidth="2" /><path d="M469 157 523 116 591 111 638 143 670 190 649 253 606 283 578 349 527 357 490 315 473 258 439 218Z" fill="#31563a" stroke="#769678" strokeWidth="2" /><path d="M669 130 741 104 811 132 860 181 900 246 879 320 830 348 784 320 738 337 701 286 669 228 636 191Z" fill="#31563a" stroke="#769678" strokeWidth="2" /><path d="M817 393 871 378 923 405 938 449 903 480 852 470 818 438Z" fill="#31563a" stroke="#769678" strokeWidth="2" /><path d="M444 410 487 394 523 414 517 467 480 494 446 475 426 440Z" fill="#31563a" stroke="#769678" strokeWidth="2" /><path d="M620 430 691 407 747 431 751 480 696 502 643 486Z" fill="#31563a" stroke="#769678" strokeWidth="2" /></svg><div className="absolute inset-0">{visiblePlaces.map((place) => <button key={place.id} type="button" aria-label={`Explore ${place.name}`} onClick={() => selectPlace(place)} className={`group absolute -translate-x-1/2 -translate-y-1/2 ${selected.id === place.id ? 'z-20' : 'z-10'}`} style={{ left: `${place.x}%`, top: `${place.y}%` }}><span className={`block rounded-full border-2 p-1 transition duration-300 ${selected.id === place.id ? 'scale-125 border-white bg-white/20' : 'border-[#b7c7a5]/70 bg-[#9caf88]/20 group-hover:scale-125'}`}><span className="block h-3 w-3 rounded-full bg-[#dfead3] shadow-[0_0_18px_rgba(223,234,211,0.9)]" /></span><span className={`absolute left-1/2 mt-3 -translate-x-1/2 whitespace-nowrap rounded-full bg-[#07100b]/80 px-2 py-1 text-[8px] uppercase tracking-[0.16em] text-white/70 transition group-hover:text-white ${selected.id === place.id ? 'opacity-100' : 'opacity-0 group-hover:opacity-100'}`}>{place.name}</span></button>)}</div><div className="absolute bottom-5 left-5 flex items-center gap-3 text-[8px] uppercase tracking-[0.2em] text-white/30"><span className="h-2 w-2 rounded-full bg-[#dfead3] shadow-[0_0_12px_#dfead3]" /> Selected location</div><div className="absolute right-5 top-5 text-right text-[8px] uppercase tracking-[0.2em] text-white/25"><p>Atlas / 01</p><p className="mt-1">Latitudes of life</p></div></div>
      </section>

      <section id="atlas-detail" className="border-y border-white/10 bg-[#0d1d13]"><div className="mx-auto grid max-w-7xl gap-10 px-6 py-16 md:grid-cols-[1.1fr_0.9fr] md:px-10 md:py-24"><div className="relative min-h-[420px] overflow-hidden rounded-2xl"><img src={selected.image} alt={selected.name} className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-[#07100b] via-transparent to-transparent" /><div className="absolute bottom-6 left-6"><p className="text-[9px] uppercase tracking-[0.3em]" style={{ color: selected.color }}>{selected.type}</p><h2 className="mt-2 text-4xl font-light">{selected.name}</h2></div></div><div className="flex flex-col justify-center"><p className="text-[10px] uppercase tracking-[0.4em]" style={{ color: selected.color }}>{selected.region} · {selected.country}</p><h3 className="mt-5 text-3xl font-light leading-tight">A place where the planet tells a different story.</h3><p className="mt-6 text-base leading-8 text-white/55">{selected.description}</p><div className="mt-8 border-l border-white/20 pl-5"><p className="text-[9px] uppercase tracking-[0.25em] text-white/30">Field note</p><p className="mt-3 text-sm leading-7 text-white/70">{selected.fact}</p></div><Link to={selected.type === 'Mountains' ? '/biomes/mountains' : selected.type === 'Ocean' ? '/biomes/oceans' : selected.type === 'Forest' ? '/biomes/forests' : '/wildlife'} className="mt-9 inline-flex w-fit border border-white/15 px-6 py-3 text-[9px] uppercase tracking-[0.25em] text-white/65 transition hover:border-[#9caf88] hover:text-[#9caf88]">Explore this world →</Link></div></div></section>

      <section className="mx-auto max-w-7xl px-6 py-24 md:px-10 md:py-32"><div className="mb-10 flex items-end justify-between"><div><p className="text-[10px] uppercase tracking-[0.4em] text-[#9caf88]">More coordinates</p><h2 className="mt-3 text-3xl font-light">Keep wandering.</h2></div><span className="text-xs text-white/25">{visiblePlaces.length} visible</span></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{visiblePlaces.map((place) => <button key={place.id} type="button" onClick={() => selectPlace(place)} className={`group relative min-h-[260px] overflow-hidden rounded-xl border text-left transition ${selected.id === place.id ? 'border-[#9caf88]/60' : 'border-white/10 hover:border-white/35'}`}><img src={place.image} alt={place.name} className="absolute inset-0 h-full w-full object-cover opacity-45 transition duration-700 group-hover:scale-105 group-hover:opacity-65" /><div className="absolute inset-0 bg-gradient-to-t from-[#07100b] via-[#07100b]/20 to-transparent" /><div className="absolute bottom-5 left-5"><p className="text-[8px] uppercase tracking-[0.22em]" style={{ color: place.color }}>{place.region}</p><h3 className="mt-2 text-xl font-light">{place.name}</h3></div></button>)}</div></section>
    </main>
  );
}
